### ISSUE TITLE
Resume Builder

### ISSUE THREAD

**Issue by priyanshi1282** [codemistic/Web-Development#131]
@gantavyamalviya hey, pls assign this issue to me under Hacktober2022.
This web app will input all your details and lets you print your resume in no time. Also this is fully responsive project.
Tech stack used - html, css, js.
Pls add hacktober22 label to this.
here is the preview of my project:
![preview](https://user-images.githubusercontent.com/88632352/193862975-74f96835-cf0b-42fd-894f-8052b11506be.png)

**Comment by OneAutumLeaf** [comment]
Hi @gantavyamalviya 
Can u assign this issue to me under Hacktoberfest 2022. I want to work on this issue
