### ISSUE TITLE
generate password

### ISSUE THREAD

**Issue by Spyder15** [codemistic/Web-Development#146]
@gantavyamalviya  hey, pls assign this issue to me under Hacktober2022.
This web app will input all your details and generate password. Also this is fully responsive project.
Tech stack used - html, css, js.
Pls add hacktober22 label to this.
here is the preview of my project:
![Image](https://user-images.githubusercontent.com/97145602/193926782-34dca331-a4ab-46b6-8044-e37ee234158e.png)

**Comment by aaushitiwari** [comment]
Can you assign me this issue?
I would like to work on it!

**Comment by Utkursraj** [comment]
Can you assign me this issue
![password Generator](https://user-images.githubusercontent.com/93482254/194221516-b60baa71-d096-492b-bf05-1ce62cc9019b.png)

**Comment by Spyder15** [comment]
@Utkursraj @aaushitiwari i already raise issue first

**Comment by aaushitiwari** [comment]
@Spyder15 is it assigned to you?
