### ISSUE TITLE
Random Gradient Generator

### ISSUE THREAD

**Issue by arun-kushwaha04** [codemistic/Web-Development#15]
Allows users to generate and experiment with random gradients for backgrounds.
Tools and Tech Stacks : JavaScript , HTML & CSS.
Please assign the issue under Hacktoberfest label

**Comment by arun-kushwaha04** [comment]
@gantavyamalviya can you kindly assign this to me

**Comment by thearyanag** [comment]
@gantavyamalviya can you please assign this issue to me
