### ISSUE TITLE
Sign in Sign up ui template 

### ISSUE THREAD

**Issue by hk2257853** [codemistic/Web-Development#165]
I'll make a sign in, sign up code template using html, css, js & bootstrap.
So people will be able to take this and customise for their apps this saving them time!

**Comment by hk2257853** [comment]
Please allow me to work on this

**Comment by aaushitiwari** [comment]
Can you assign me this issue?
I would like to work on it!

**Comment by shardendu930** [comment]
Hii I am Shardendu Kumar . I will make a sign in , sign up code template and I will make it responsive and beautiful . Please assign me this issue . I would like to work on it.
