### ISSUE TITLE
Tea selling website (Btech Chaiwala)

### ISSUE THREAD

**Issue by ilhamansari** [codemistic/Web-Development#238]
A tea selling website made by using html and css.
The project is already ready . Here's a glimpse of the project.
![Screenshot (38)](https://user-images.githubusercontent.com/102286043/194314223-218c4cac-009e-4bee-8263-eba112445844.png)
![Screenshot (39)](https://user-images.githubusercontent.com/102286043/194314233-52a9e6ba-ae54-46d2-8f56-37e17e2ffa95.png)

So please assign me this issue under hacktoberfest2022.

**Comment by Purva2803** [comment]
I want to do some UI changes in this project please assign me this issue.
