### ISSUE TITLE
Add Dictionary Web App

### ISSUE THREAD

**Issue by Aayushi-Mittal** [codemistic/Web-Development#341]
A Progressive Web App which serves as a pocket dictionary! Users can check the meanings, synonyms, pronunciations, etc of a word.
**Tech Stack:** Node JS, React JS, Material UI, APIs
Can I add the code for this project?

**Comment by projectsop** [comment]
Why the contributors are here then we will add soon

**Comment by projectsop** [comment]
Close it and directly create pull request

**Comment by Aayushi-Mittal** [comment]
Sure, Creating a pull request. Sorry for the inconvenience.

**Comment by projectsop** [comment]
The moderators will accept your pr within few hours pls wait after opening pr

**Comment by projectsop** [comment]
Close this now
