### ISSUE TITLE
Trimmer reselling website

### ISSUE THREAD

**Issue by mihir224** [codemistic/Web-Development#360]
Hi @gantavyamalviya @Adarsh-jaiss. I want to add a trimmer reselling website project I made to this repo. Please add this issue under Hacktoberfest 2022 and assign it to me. 
Thank you

**Comment by projectsop** [comment]
Not needed. Directly add the code and send a pull request. Let moderators decide whether your project will be added or not....

**Comment by mihir224** [comment]
got it
