### ISSUE TITLE
Should add descriptive Contributing guideline

### ISSUE THREAD

**Issue by ZaidKhan2002** [codemistic/Web-Development#367]
There should be clear concise markdown file for contribution.

**Comment by projectsop** [comment]
Not needed as users can add any type of file.
That FILE will be checked by the maintainers and they will decide whether the file will merged or not with hacktoberfest and hacktoberfest-accepted levels.
Close the issue now

Thanks,
@projectsop

**Comment by ZaidKhan2002** [comment]
Sure.
