### ISSUE TITLE
Sign up form

### ISSUE THREAD

**Issue by sohamdata** [codemistic/Web-Development#44]
A simple sign up form.
Please assign the issue under `hacktoberfest` label

**Comment by Adilkhan656** [comment]
Hi.....please assign me this issue

**Comment by itsaman123** [comment]
Hello sir,
please assign me this issue

**Comment by Purva2803** [comment]
I really want to work on this issue please assign it to me.

**Comment by akanksha0214** [comment]
Hello, I want to work on this issue please assign this to me.
